entrada = input()
entrada = entrada.split(" ")
a = round(float(entrada[0]), 2)
b = round(float(entrada[1]), 2)
c = round(float(entrada[2]), 2)
print("TRIANGULO: {:.3f}".format((a*c)/2))
print("CIRCULO: {:.3f}".format(c**2*3.14159))
print("TRAPEZIO: {:.3f}".format(((a+b)*c)/2))
print("QUADRADO: {:.3f}".format(b**2))
print("RETANGULO: {:.3f}".format(a*b))